config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'

  get 'auth', to: 'user#auth', as: 'auth'
  get 'access', to: 'user#access', as: 'access'

  get 'gw_message', to: 'router#message', as: 'message'
  get 'ping', to: 'router#ping', as: 'ping'
  get 'portal', to: 'router#portal', as: 'portal'

  namespace :admin do
    root to: 'dashboard#show'

    get 'login', to: 'sessions#new', as: 'login'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    resource :router, only: [:show, :edit, :update]
    resources :users
  end
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :user

  before_create :check_time

  private

  def check_time
    time_now = Time.now.min + 60*Time.now.hour
    wday_now = Time.now.wday
    month_now = Time.now.mon
    time_intervals, wday_interval, month_interval = parse_signin_conf

    time_interval_include = false
    time_intervals.each do |time_interval|
      break if time_interval_include = (time_now > time_interval.first && time_now < time_interval.last)
    end

    time_interval_include && wday_interval.include?(wday_now) && month_interval.include?(month_now)
  end

  def parse_signin_conf
    router = self.user.router
    signin_conf = JSON.parse(router.signin_conf)
    [signin_conf["time_intervals"], signin_conf["wday_interval"], signin_conf["month_interval"]]
  end
end

app/models/router.rb
class Router < ActiveRecord::Base
  has_many :users

  def set_signin_conf(signin_conf = {
                      time_intervals: [[0, 1440]],
                      wday_interval: (1..7).to_a,
                      month_interval: (1..12).to_a})
    signin_conf_orig = JSON.parse self.signin_conf
    signin_conf.each do |key, value|
      signin_conf_orig[key.to_s] = value if signin_conf_orig[key.to_s]
    end
    self.signin_conf = JSON.generate signin_conf_orig
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :attendances, dependent: :destroy
  belongs_to :router

  validates :name, presence: true, uniqueness: true
  validates :mac_addr, uniqueness: true, allow_nil: true

  def admin?
    router.admin_ids.include?(id)
  end
end

app/controllers/admin/application.rb
class Admin::ApplicationController < ApplicationController
  before_action :login_required

  private

  def login_required
    unless session[:admin_id].present?
      redirect_to admin_login_url
    end
  end

  def login_as(user)
    session[:admin_id] = user.id
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  layout 'admin'

  before_action :login_required
  before_action :find_router

  private

  def find_router
    @router = Router.first
  end

  def login_required
    unless session[:admin_id].present?
      redirect_to admin_login_url
    end
  end

  def login_as(user)
    session[:admin_id] = user.id
  end

  def logout
    session.delete(:admin_id)
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def show
  end
end

app/controllers/admin/routers_controller.rb
class Admin::RoutersController < Admin::ApplicationController
  def show
  end

  def edit
  end

  def update
    if @router.update(router_params)
      redirect_to admin_router_url
    else
      render 'edit'
    end
  end

  private

  def router_params
    params.require(:router).permit(:name)
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::ApplicationController
  layout false

  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    @user = User.find_by(name: login_params[:name])

    if @user && @user.authenticate(login_params[:password]) && @user.admin?
      login_as @user
      redirect_to admin_root_url
    else
      flash[:now] = '用户名或密码错误，或该用户非管理员'
      render :new
    end
  end

  def destroy
    logout
    redirect_to admin_login_url
  end

  private

  def login_params
    params.require(:user).permit(:name, :password)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = @router.users.order(:id)
  end

  def new
    @user = User.new
  end

  def create
    begin
      @router.users.create!(user_params.slice(:name, :password))
      @users = @router.users.all.order(:id)
    rescue ActiveRecord::RecordInvalid
      @users = nil
    end
  end

  def show
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to admin_user_url(@user)
  end

  def destroy
    @user.destroy
    redirect_to admin_users_url
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :password, :mac_addr)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception. 
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def wifi_auth_url(gw_address, gw_port, token)
    "http://#{gw_address}:#{gw_port}/wifidog/auth?token=#{token}"
  end

  def token_for(user, token_secret)
    user.name.bytes.map { |byte| (byte^token_secret).chr }.join
  end

  def get_name_from_token(token, token_secret)
    token.bytes.map { |byte| (byte^token_secret).chr }.join
  end
end

app/controllers/router_controller.rb
class RouterController < ApplicationController
  def message
    flash[:now] = params[:message]
  end

  def ping
    router = Router.find_by(gw_id: params[:gw_id])
    router_params = params.slice(:sys_uptime, :sys_load, :sys_memfree, :wifidog_uptime).symbolize_keys
    router.update(router_params)
    render plain: 'Pong'
  end

  def portal
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    session.merge!(params.slice(:gw_address, :gw_port, :gw_id, :url))
  end

  def create
    @user = User.find_by(name: login_params[:name])

    if @user && @user.authenticate(login_params[:password])
      token = token_for(@user, 7)
      redirect_to wifi_auth_url(session[:gw_address], session[:gw_port], token)
    else
      flash[:now] = '用户名或密码错误，请重新登录'
      render :new
    end
  end

  private

  def login_params
    params.require(:user).permit(:name, :password)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def auth
    case params[:stage]
    when 'login'
      name = get_name_from_token(params[:token], 7)
      user = User.find_by(name: name)
      if user && params[:mac]
        bind_or_deny(user, params[:mac])
      else
        render plain: Auth_status[:denied]
      end
    else
      render plain: Auth_status[:allowed]
    end
  end

  def access
    user_mac_addr = params[:user_mac_addr]
    router_mac_addr = params[:router_mac_addr]

    unless user_mac_addr && router_mac_addr && Router.exists?(gw_id: router_mac_addr)
      return render plain: Bound_status(router_mac_addr, :params_error)
    end

    if User.exists?(
      router_id: Router.find_by(gw_id: router_mac_addr),
      mac_addr: user_mac_addr)
      User.find_by(mac_addr: user_mac_addr).attendances.create
      render plain: Bound_status(router_mac_addr, :bound)
    else
      render plain: Bound_status(router_mac_addr, :unbound)
    end
  end

  private

  Auth_status = {
    allowed: 'Auth: 1',
    denied: 'Auth: 0'
  }

  Bound_status = {
    bound: 'Bound: 1',
    unbound: 'Bound: 0',
    params_error: 'Bound: -1'
  }

  def Bound_status(router_mac_addr, status)
    "gw_id: #{router_mac_addr} Bound: #{Bound_status[status]}"
  end

  def bind_or_deny(user, mac_addr)
    case user.mac_addr
    when nil
      user.mac_addr = mac_addr
      if user.save
        user.attendances.create
        render plain: Auth_status[:allowed]
      else
        render plain: Auth_status[:denied]
      end
    when mac_addr
      user.attendances.create
      render plain: Auth_status[:allowed]
    else
      render plain: Auth_status[:denied]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/attendances/_attendance.html.erb
<h1>User - Attendances</h1>

<div>
<table>
  <tr>
    <th>ID</th>
    <th>Time</th>
  </tr>

  <tr>
    <td><%= attendance.id %></td>
    <td><%= attendance.created_at %></td>
  </tr>
</table>
</div>

app/views/admin/dashboard/show.html.erb
<h1>Admin - Dashboard</h1>
<%= link_to 'Router', admin_router_url %>
<%= link_to 'Users', admin_users_url %>
<%= link_to 'logout', admin_logout_url, method: :delete %>

app/views/admin/routers/edit.html.erb
<h1>Edit Router</h1>
<%= form_for :router, url: admin_router_url, method: :patch do |f| %>
  <div>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>

  <div>
  <%= f.submit %>
  </div>
<% end %>

app/views/admin/routers/show.html.erb
<h1>Router</h1>

<div>
<% @router.attributes.each do |key, value| %>
  <p><%= "#{key}: #{value}" %></p>
<% end %>
</div>

<div>
<%= link_to "Edit", edit_admin_router_url %>
</div>

<div>
<%= link_to "Dashboard", admin_root_url %>
</div>

app/views/admin/users/_user.html.slim
.user-info-box.mdl-shadow--2dp data-user-id=user.id
  .user-icon-container.mdl-cell.mdl-cell--2-col.mdl-cell--1-col-phone.material-icons face
  .user-info.mdl-cell.mdl-cell--10-col-desktop.mdl.cell--6-tablet.mdl-cell--3-col-phone
    h5 = user.name
    - if user.mac_addr
      p style="color: #46B6AC" 已绑定
    - else
      p style="color: #F44336" 未绑定

app/views/admin/users/create.js.erb
<% if @users %>
  $('.user-container').html('<%= j (render @users) %>');
  $('.user-container').append('<div class="create-user-box mdl-shadow--2dp"><div class="plus-icon-container mdl-cell mdl-cell--col-2 mdl-cell--1-col-phone material-icons">add_circle_outline</div>');
  $('#user-name').val('');
  $('#user-password').val('');
  $('.form-container').slideUp(350);
<% else %>
  alert('error');
<% end %>

app/views/admin/users/edit.html.erb
<h1>Edit User</h1>
<%= form_for :user, url: admin_user_url, method: :patch do |f| %>
  <div>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>

  <div>
  <%= f.label :mac_addr %>
  <%= f.text_field :mac_addr %>
  </div>

  <div>
  <%= f.label :password %>
  <%= f.password_field :password %>
  </div>

  <div>
  <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/index.html.slim
- @page_title = '用户列表'

.mdl-card__supporting-text.mdl-grid.mdl-grid--no-spacing.user-container
  = render @users
  .create-user-box.mdl-shadow--2dp
    .plus-icon-container.mdl-cell.mdl-cell--col-2.mdl-cell--1-col-phone.material-icons add_circle_outline
.mdl-card__supporting-text.mdl-grid.mdl-grid--no-spacing.form-container style="display: none"
  = form_tag admin_users_url, remote: true do
    .form-group.mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
       = text_field_tag "user[name]", nil, class: "mdl-textfield__input", id: "user-name"
       = label_tag "用户名", nil, class: "mdl-textfield__label", for: "user-name"
    .form-group.mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
      = text_field_tag "user[password]", nil, class: "mdl-textfield__input", id: "user-password", onfocus: "this.type='password'"
      = label_tag "密码", nil, class: "mdl-textfield__label", for: "user-password"
    .form-group
      = submit_tag "创建用户", class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored", id: "submit-button"
  .slide-up-icon.material-icons.mdl-button.mdl-js-button expand_less

javascript:
  $('body').on('click', '.user-info-box', function(){
    var userId = $(this).data('user-id');
    var userUrl = "#{admin_users_url}/" + userId;
    window.location.href = userUrl;
  });

  $('.slide-up-icon').click(function() {
    $('.form-container').slideUp(350);
  });

app/views/admin/users/new.html.erb
<h1>新建用户</h1>
<%= form_for @user, url: admin_users_url do |f| %>
  <div>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>

  <div>
  <%= f.label :password %>
  <%= f.password_field :password %>
  </div>

  <div>
  <%= f.submit '新建' %>
  </div>
<% end %>

app/views/admin/users/show.html.slim
.mdl-card__supporting-text.mdl-grid.mdl-grid--no-spacing.user-profile
  .mdl-grid.mdl-grid--4-col.user-profile-title
    .user-icon-container.material-icons perm_identity
    h1 = @user.name
  .user-profile-container
    .user-profile-name.user-attributes-container.mdl-textfield.mdl-js-textfield
      | 姓名：
      p
        = @user.name
      input.mdl-textfield__input type="text" style="display: none"
    .user-profile-attendance-count.user-attributes-container.pull-right
      p
        | 签到次数：
        = @user.attendances.count
    .user-profile-edit.material-icons.mdl-button.mdl-js-button#user-edit edit
    .mdl-tooltip for="user-edit" 编辑用户信息
    .user-profile-status.user-attributes-container
      p
        | 用户状态：
        - if @user.mac_addr
          | 已绑定
        - else
          | 未绑定
    .user-profile-mac-addr.user-attributes-container.pull-right
      p
        | MAC 地址：
        - if @user.mac_addr
          = @user.mac_addr
        - else
          | -
    .user-profile-edit.material-icons.mdl-button.mdl-js-button#user-unbound lock_open
    .mdl-tooltip for="user-unbound"
      - if @user.mac_addr
        | 取消绑定
      - else
        | 未绑定
  .user-attendances-container

css:
  .mdl-card__actions {
    background-color: #EEEEEE !important;
  }

javascript:
  $(document).ready(function() {
    if (!$('.mdl-card__title').html().includes('user-id-container')) {
      $('.mdl-card__title').append('<div class="user-id-container">USER ID #{@user.id}</div>');
      $('.mdl-card__actions').append('<div class="material-icons mdl-button mdl-js-button back-icon">chevron_left</div>');
      $('.mdl-card__actions').append('<div class="material-icons mdl-button mdl-js-button trash-icon">delete</div>');
    }

    $('.back-icon').click(function() {
      window.location.href="/admin/users";
    });
  });

app/views/layouts/admin.html.slim
doctype html
html
  head
    title
      = @page_title ? "#{@page_title} - 管理后台" : "管理后台"
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    meta name="viewport" content="width=device-width, initial-scale=1.0"

  body
    .mdl-layout.mdl-js-layout.mdl-layout--fixed-header.mdl-layout--fixed-drawer
      header.mdl-layout__header.mdl-color--white.mdl-color--grey-100.mdl-color-text--grey-600.is-casting-shadow
        .mdl-layout__header-row
          span.mdl-layout-title
            = @page_title ? "#{@page_title} - 管理后台" : "管理后台"
          .mdl-layout-spacer
          a.mdl-button.mdl-js-icon.mdl-button--icon id="home-icon" href="/admin"
            i.material-icons dashboard
          .mdl-tooltip for="home-icon" 主页
      .admin-drawer.mdl-layout__drawer.mdl-color-text--blue-grey-50
        header.admin-drawer-header
          = image_tag "skylark.png", class: "admin-logo"
          .admin-admin-info
            span Administrator
            .mdl-layout-spacer
            button.mdl-button.mdl-js-icon.mdl-button--icon id="admin-drawer-dropdown"
              i.material-icons arrow_drop_down
            ul.mdl-menu.mdl-menu--bottom-right.mdl-js-menu.mdl-js-ripple-effect for="admin-drawer-dropdown"
              li.mdl-menu__item
                a href=""
                  | 修改密码
                  i.material-icons edit
              .admin-menu-separator
              li.mdl-menu__item
                a data-method="delete" href=admin_logout_url
                  | 退出登录
                  i.material-icons exit_to_app
        nav.admin-navigation.mdl-navigation
          span.mdl-navigation__link
            i.mdl-color-text--blue-grey-400.material-icons role="presentation" account_circle
            | 用户管理
          a.mdl-navigation__link id="user_index" href=admin_users_url
            i.mdl-color-text--blue-grey-400.material-icons role="presentation" group
            | 用户列表
          a.mdl-navigation__link href=""
            i.mdl-color-text--blue-grey-400.material-icons role="presentation" assignment
            | 签到情况
          .admin-drawer-separator
          span.mdl-navigation__link
            i.mdl-color-text--blue-grey-400.material-icons role="presentation" network_wifi
            | 路由管理
          a.mdl-navigation__link id="router_show" href=admin_router_url
            i.mdl-color-text--blue-grey-400.material-icons role="presentation" info
            | 路由信息
          a.mdl-navigation__link id="router_edit" href=edit_admin_router_url
            i.mdl-color-text--blue-grey-400.material-icons role="presentation" edit
            | 编辑路由
          .admin-drawer-separator
          span.mdl-navigation__link
            i.mdl-color-text--blue-grey-400.material-icons role="presentation" settings
            | 设置
          a.mdl-navigation__link href=""
            i.mdl-color-text--blue-grey-400.material-icons role="presentation" rate_review
            | 签到设置
          .mdl-layout-spacer
          a.mdl-navigation__link href=""
            i.mdl-color-text--blue-grey-400.material-icons role="presentation" help_outline

      main.mdl-layout__content.mdl-color--grey-100
        .page-content.mdl-card.mdl-color--white.mdl-shadow--4dp.mdl-cell.mdl-cell--12-col.mdl-grid
          .mdl-card__title.mdl-card--expand
            h2.mdl-card__title-text
              = @page_title ? @page_title : ""
          .page-content-container
            = yield
          .mdl-card__actions

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuthServer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/router/message.html.erb
<% if !flash[:now].nil? %>
    <p>发生错误，错误代码为<%= flash[:now] %></p>
<% else %>
    <p>发生未知错误</p>
<% end %>

app/views/router/portal.html.erb
<p>登录成功，用户已绑定！</p>